name: CI
 
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CSV_URL: "MLproject/train_pca.csv"
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cek variabel lingkungan
      - name: Check Env
        run: echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.18.0 cloudpickle==3.1.1 numpy==2.2.6 pandas==2.2.3 scikit-learn==1.6.1 scipy==1.15.3

      # Jalankan MLflow Project
      - name: Run mlflow project
        run: mlflow run . --env-manager=local

      # Simpan hasil mlruns ke repository
      - name: Save mlruns to repo
        env:
          PAT_TOKEN: ${{ secrets.PAT_GITHUB }}  # Gunakan secret token yang benar
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git pull origin master
          git add mlruns/
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"
          git remote set-url origin https://${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:master
